// UFC Oracle v4.1 — Discord test script
// Sends a realistic mock fight card predictions + recap to verify webhook + embed format.
// Run: node --loader ts-node/esm src/test-discord.ts

import 'dotenv/config';
import type { Prediction, AccuracyStats } from './types.js';
import { sendFightCardPredictions, sendPostEventRecap, type RecapResult } from './discord/discord.js';

// ─── Mock fight card: UFC 314 (April 12, 2026) ───────────────────────────────

const mockPredictions: Prediction[] = [
  {
    predictionId: 'test-001',
    fightId: 'ufc314-0',
    eventId: 'ufc314',
    eventName: 'UFC 314: Poirier vs Gaethje 2',
    eventDate: '2026-04-12',
    fighterAId: 'poirier',
    fighterBId: 'gaethje',
    fighterAName: 'Dustin Poirier',
    fighterBName: 'Justin Gaethje',
    weightClass: 'Lightweight',
    cardPosition: 'main_event',
    isMainEvent: true,
    isTitleFight: false,
    scheduledRounds: 5,
    featureVector: {} as never,
    fighterAWinProb: 0.58,
    fighterBWinProb: 0.42,
    predictedWinnerId: 'poirier',
    predictedWinnerName: 'Dustin Poirier',
    confidenceTier: 'strong',
    koProb: 0.41,
    submissionProb: 0.09,
    decisionProb: 0.45,
    otherProb: 0.05,
    predictedMethod: 'Decision',
    fighterAMoneyline: -140,
    fighterBMoneyline: 115,
    vegasWinnerProb: 0.583,
    edge: -0.003,
    edgeCategory: 'none',
    modelVersion: '4.1.0',
    createdAt: new Date().toISOString(),
  },
  {
    predictionId: 'test-002',
    fightId: 'ufc314-1',
    eventId: 'ufc314',
    eventName: 'UFC 314: Poirier vs Gaethje 2',
    eventDate: '2026-04-12',
    fighterAId: 'ankalaev',
    fighterBId: 'rakic',
    fighterAName: 'Magomed Ankalaev',
    fighterBName: 'Aleksandar Rakic',
    weightClass: 'LightHeavyweight',
    cardPosition: 'co_main',
    isMainEvent: false,
    isTitleFight: true,
    scheduledRounds: 5,
    featureVector: {} as never,
    fighterAWinProb: 0.71,
    fighterBWinProb: 0.29,
    predictedWinnerId: 'ankalaev',
    predictedWinnerName: 'Magomed Ankalaev',
    confidenceTier: 'high_conviction',
    koProb: 0.32,
    submissionProb: 0.08,
    decisionProb: 0.55,
    otherProb: 0.05,
    predictedMethod: 'Decision',
    fighterAMoneyline: -210,
    fighterBMoneyline: 170,
    vegasWinnerProb: 0.677,
    edge: 0.033,
    edgeCategory: 'none',
    modelVersion: '4.1.0',
    createdAt: new Date().toISOString(),
  },
  {
    predictionId: 'test-003',
    fightId: 'ufc314-2',
    eventId: 'ufc314',
    eventName: 'UFC 314: Poirier vs Gaethje 2',
    eventDate: '2026-04-12',
    fighterAId: 'vettori',
    fighterBId: 'strickland',
    fighterAName: 'Marvin Vettori',
    fighterBName: 'Sean Strickland',
    weightClass: 'Middleweight',
    cardPosition: 'main_card',
    isMainEvent: false,
    isTitleFight: false,
    scheduledRounds: 3,
    featureVector: {} as never,
    fighterAWinProb: 0.39,
    fighterBWinProb: 0.61,
    predictedWinnerId: 'strickland',
    predictedWinnerName: 'Sean Strickland',
    confidenceTier: 'strong',
    koProb: 0.15,
    submissionProb: 0.07,
    decisionProb: 0.73,
    otherProb: 0.05,
    predictedMethod: 'Decision',
    fighterAMoneyline: 155,
    fighterBMoneyline: -185,
    vegasWinnerProb: 0.649,
    edge: -0.039,
    edgeCategory: 'none',
    modelVersion: '4.1.0',
    createdAt: new Date().toISOString(),
  },
  {
    predictionId: 'test-004',
    fightId: 'ufc314-3',
    eventId: 'ufc314',
    eventName: 'UFC 314: Poirier vs Gaethje 2',
    eventDate: '2026-04-12',
    fighterAId: 'topuria-e',
    fighterBId: 'allen-arnold',
    fighterAName: 'Ilia Topuria',
    fighterBName: 'Arnold Allen',
    weightClass: 'Featherweight',
    cardPosition: 'main_card',
    isMainEvent: false,
    isTitleFight: false,
    scheduledRounds: 3,
    featureVector: {} as never,
    fighterAWinProb: 0.76,
    fighterBWinProb: 0.24,
    predictedWinnerId: 'topuria-e',
    predictedWinnerName: 'Ilia Topuria',
    confidenceTier: 'lock',
    koProb: 0.54,
    submissionProb: 0.12,
    decisionProb: 0.29,
    otherProb: 0.05,
    predictedMethod: 'KO/TKO',
    fighterAMoneyline: -340,
    fighterBMoneyline: 265,
    vegasWinnerProb: 0.773,
    edge: -0.013,
    edgeCategory: 'none',
    modelVersion: '4.1.0',
    createdAt: new Date().toISOString(),
  },
  {
    predictionId: 'test-005',
    fightId: 'ufc314-4',
    eventId: 'ufc314',
    eventName: 'UFC 314: Poirier vs Gaethje 2',
    eventDate: '2026-04-12',
    fighterAId: 'ramos-b',
    fighterBId: 'santos-thiago',
    fighterAName: 'Bruno Ramos',
    fighterBName: 'Thiago Santos',
    weightClass: 'LightHeavyweight',
    cardPosition: 'prelim',
    isMainEvent: false,
    isTitleFight: false,
    scheduledRounds: 3,
    featureVector: {} as never,
    fighterAWinProb: 0.34,
    fighterBWinProb: 0.66,
    predictedWinnerId: 'santos-thiago',
    predictedWinnerName: 'Thiago Santos',
    confidenceTier: 'strong',
    koProb: 0.38,
    submissionProb: 0.06,
    decisionProb: 0.51,
    otherProb: 0.05,
    predictedMethod: 'Decision',
    fighterAMoneyline: 195,
    fighterBMoneyline: -240,
    vegasWinnerProb: 0.706,
    edge: -0.046,
    edgeCategory: 'none',
    modelVersion: '4.1.0',
    createdAt: new Date().toISOString(),
  },
  {
    predictionId: 'test-006',
    fightId: 'ufc314-5',
    eventId: 'ufc314',
    eventName: 'UFC 314: Poirier vs Gaethje 2',
    eventDate: '2026-04-12',
    fighterAId: 'hernandez-carlos',
    fighterBId: 'dober-drew',
    fighterAName: 'Carlos Hernandez',
    fighterBName: 'Drew Dober',
    weightClass: 'Lightweight',
    cardPosition: 'prelim',
    isMainEvent: false,
    isTitleFight: false,
    scheduledRounds: 3,
    featureVector: {} as never,
    fighterAWinProb: 0.62,
    fighterBWinProb: 0.38,
    predictedWinnerId: 'hernandez-carlos',
    predictedWinnerName: 'Carlos Hernandez',
    confidenceTier: 'strong',
    koProb: 0.29,
    submissionProb: 0.22,
    decisionProb: 0.44,
    otherProb: 0.05,
    predictedMethod: 'Decision',
    fighterAMoneyline: -155,
    fighterBMoneyline: 128,
    vegasWinnerProb: 0.608,
    edge: 0.012,
    edgeCategory: 'none',
    modelVersion: '4.1.0',
    createdAt: new Date().toISOString(),
  },
  {
    predictionId: 'test-007',
    fightId: 'ufc314-6',
    eventId: 'ufc314',
    eventName: 'UFC 314: Poirier vs Gaethje 2',
    eventDate: '2026-04-12',
    fighterAId: 'lima-tony',
    fighterBId: 'goncalves-cody',
    fighterAName: 'Tony Lima',
    fighterBName: 'Cody Goncalves',
    weightClass: 'Welterweight',
    cardPosition: 'early_prelim',
    isMainEvent: false,
    isTitleFight: false,
    scheduledRounds: 3,
    featureVector: {} as never,
    fighterAWinProb: 0.44,
    fighterBWinProb: 0.56,
    predictedWinnerId: 'goncalves-cody',
    predictedWinnerName: 'Cody Goncalves',
    confidenceTier: 'lean',
    koProb: 0.21,
    submissionProb: 0.18,
    decisionProb: 0.56,
    otherProb: 0.05,
    predictedMethod: 'Decision',
    modelVersion: '4.1.0',
    createdAt: new Date().toISOString(),
  },
];

const mockStats: AccuracyStats = {
  ytdCorrect: 187,
  ytdTotal: 274,
  ytdAccuracy: 0.682,
  highConvCorrect: 54,
  highConvTotal: 73,
  highConvAccuracy: 0.740,
  methodCorrect: 89,
  methodTotal: 210,
  methodAccuracy: 0.424,
  valueBetROI: 0.063,
  underdogCorrect: 28,
  underdogTotal: 71,
  mainEventCorrect: 24,
  mainEventTotal: 34,
  brierScore: 0.209,
  eventRecord: [
    { eventId: 'ufc313', eventName: 'UFC 313', eventDate: '2026-03-08', correct: 8, total: 12, accuracy: 0.667 },
    { eventId: 'ufc-fnfeb', eventName: 'UFC Fight Night Feb', eventDate: '2026-02-22', correct: 7, total: 11, accuracy: 0.636 },
    { eventId: 'ufc312', eventName: 'UFC 312', eventDate: '2026-02-08', correct: 9, total: 13, accuracy: 0.692 },
  ],
};

// ─── Mock recap results ───────────────────────────────────────────────────────

const mockRecapResults: RecapResult[] = [
  {
    prediction: { ...mockPredictions[0], correct: false, methodCorrect: false, actualWinnerId: 'gaethje', actualMethod: 'KO/TKO' },
    actualWinnerName: 'Justin Gaethje',
    method: 'KO/TKO',
    round: 2,
  },
  {
    prediction: { ...mockPredictions[1], correct: true, methodCorrect: true, actualWinnerId: 'ankalaev', actualMethod: 'Decision' },
    actualWinnerName: 'Magomed Ankalaev',
    method: 'Decision',
    round: 5,
  },
  {
    prediction: { ...mockPredictions[2], correct: true, methodCorrect: true, actualWinnerId: 'strickland', actualMethod: 'Decision' },
    actualWinnerName: 'Sean Strickland',
    method: 'Decision',
    round: 3,
  },
  {
    prediction: { ...mockPredictions[3], correct: true, methodCorrect: true, actualWinnerId: 'topuria-e', actualMethod: 'KO/TKO' },
    actualWinnerName: 'Ilia Topuria',
    method: 'KO/TKO',
    round: 1,
  },
  {
    prediction: { ...mockPredictions[4], correct: false, methodCorrect: false, actualWinnerId: 'ramos-b', actualMethod: 'Submission' },
    actualWinnerName: 'Bruno Ramos',
    method: 'Submission',
    round: 2,
  },
  {
    prediction: { ...mockPredictions[5], correct: true, methodCorrect: false, actualWinnerId: 'hernandez-carlos', actualMethod: 'Submission' },
    actualWinnerName: 'Carlos Hernandez',
    method: 'Submission',
    round: 3,
  },
  {
    prediction: { ...mockPredictions[6], correct: true, methodCorrect: true, actualWinnerId: 'goncalves-cody', actualMethod: 'Decision' },
    actualWinnerName: 'Cody Goncalves',
    method: 'Decision',
    round: 3,
  },
];

const recapStats: AccuracyStats = {
  ...mockStats,
  ytdCorrect: 192,
  ytdTotal: 281,
  ytdAccuracy: 0.683,
  highConvCorrect: 56,
  highConvTotal: 75,
  highConvAccuracy: 0.747,
};

// ─── Run ──────────────────────────────────────────────────────────────────────

async function main() {
  const mode = process.argv[2]; // 'picks' | 'recap' | (both if omitted)

  if (!mode || mode === 'picks') {
    console.log('Sending fight card predictions embed...');
    const ok = await sendFightCardPredictions(mockPredictions, mockStats, false);
    console.log(ok ? '✅ Predictions sent' : '❌ Predictions failed');
  }

  if (!mode || mode === 'recap') {
    // Small delay so they appear in order in Discord
    if (!mode) await new Promise(r => setTimeout(r, 2000));
    console.log('Sending post-event recap embed...');
    const ok = await sendPostEventRecap(mockRecapResults, recapStats);
    console.log(ok ? '✅ Recap sent' : '❌ Recap failed');
  }
}

main().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
